# 🔢 NumPy Workshop — Linear Algebra Foundations (Student Edition)

Welcome! This notebook teaches **NumPy** for linear algebra — the mathematical foundation of machine learning.  
We will connect concepts from linear algebra (vectors, matrices, determinants, rank, eigenvalues, etc.) to **practical NumPy code**.

### What we'll learn
- NumPy basics: arrays, shapes, dtypes
- Vectors: creation, arithmetic, dot product, cosine similarity
- Matrices: creation, transpose, addition, multiplication
- Linear transformations with matrices
- Rank, determinant, inverse
- Solving linear systems
- Eigenvalues & eigenvectors
- Singular Value Decomposition (SVD)
- Practice exercises + worked solutions

---


## 0) Setup

**Goal:** Import NumPy and check environment versions.

**What this does:**
- Imports `numpy` and sets alias `np`
- Prints NumPy version for consistency


In [1]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 2.3.2


## 1) NumPy arrays basics

**Goal:** Understand how to create arrays, check shape, and dtype.

**What this does:**
- Creates 1D, 2D, and 3D arrays
- Prints shape (dimensions) and dtype (data type)


In [2]:
# Create arrays
a = np.array([1, 2, 3])           # 1D vector
b = np.array([[1, 2], [3, 4]])    # 2D matrix
c = np.ones((2, 3))               # 2D matrix filled with ones
d = np.random.rand(2, 2, 2)       # 3D tensor

print("a:", a, "shape:", a.shape)
print("b:\n", b, "shape:", b.shape)
print("c:\n", c, "dtype:", c.dtype)
print("d shape:", d.shape)


a: [1 2 3] shape: (3,)
b:
 [[1 2]
 [3 4]] shape: (2, 2)
c:
 [[1. 1. 1.]
 [1. 1. 1.]] dtype: float64
d shape: (2, 2, 2)


## 2) Vectors

**Goal:** Perform basic vector operations.

**What this does:**
- Creates 1D arrays (vectors)
- Demonstrates addition, subtraction, scalar multiplication
- Computes dot product and cosine similarity


In [3]:
# Define two vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Basic operations
print("v1 + v2 =", v1 + v2)
print("v1 - v2 =", v1 - v2)
print("2 * v1 =", 2 * v1)

# Dot product
dot = np.dot(v1, v2)
print("Dot product =", dot)

# Cosine similarity
cos_sim = dot / (np.linalg.norm(v1) * np.linalg.norm(v2))
print("Cosine similarity =", cos_sim)


v1 + v2 = [5 7 9]
v1 - v2 = [-3 -3 -3]
2 * v1 = [2 4 6]
Dot product = 32
Cosine similarity = 0.9746318461970762


## 3) Matrices

**Goal:** Work with 2D arrays (matrices).

**What this does:**
- Creates a matrix
- Computes transpose
- Performs matrix addition and multiplication


In [4]:
# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Transpose of A:\n", A.T)

# Addition
print("A + B:\n", A + B)

# Matrix multiplication
print("A @ B:\n", A @ B)


Matrix A:
 [[1 2]
 [3 4]]
Transpose of A:
 [[1 3]
 [2 4]]
A + B:
 [[ 6  8]
 [10 12]]
A @ B:
 [[19 22]
 [43 50]]


## 4) Linear transformations

**Goal:** Show how matrices transform vectors.

**What this does:**
- Defines a 2D rotation matrix (90°)
- Applies it to a vector
- Interprets the result as rotation in the plane


In [5]:
# Define a 90-degree rotation matrix
theta = np.pi / 2
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])

vec = np.array([1, 0])

print("Original vector:", vec)
print("Rotated vector:", R @ vec)


Original vector: [1 0]
Rotated vector: [6.123234e-17 1.000000e+00]


## 5) Rank and determinant

**Goal:** Learn matrix properties related to invertibility and independence.

**What this does:**
- Uses `np.linalg.matrix_rank` to compute rank
- Uses `np.linalg.det` to compute determinant


In [6]:
M = np.array([[2, 4], [1, 2]])  # Second row is 0.5 * first row

print("Matrix M:\n", M)
print("Rank:", np.linalg.matrix_rank(M))
print("Determinant:", np.linalg.det(M))


Matrix M:
 [[2 4]
 [1 2]]
Rank: 1
Determinant: 0.0


## 6) Inverse & solving linear systems

**Goal:** Use NumPy to invert matrices and solve equations.

**What this does:**
- Uses `np.linalg.inv` to compute matrix inverse
- Solves Ax = b using `np.linalg.solve`


In [7]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

# Inverse
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

# Solve Ax = b
x = np.linalg.solve(A, b)
print("Solution x:", x)


Inverse of A:
 [[ 0.4 -0.2]
 [-0.2  0.6]]
Solution x: [2. 3.]


## 7) Eigenvalues & eigenvectors

**Goal:** Find directions that remain unchanged under a matrix transformation.

**What this does:**
- Uses `np.linalg.eig` to compute eigenvalues and eigenvectors
- Interprets them as scaling factors and invariant directions


In [8]:
C = np.array([[4, -2], 
              [1,  1]])

eigvals, eigvecs = np.linalg.eig(C)

print("Matrix C:\n", C)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)


Matrix C:
 [[ 4 -2]
 [ 1  1]]
Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


## 8) Singular Value Decomposition (SVD)

**Goal:** Decompose a matrix into three parts for dimensionality reduction.

**What this does:**
- Uses `np.linalg.svd`
- Prints U, S, V^T matrices


In [9]:
D = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]])

U, S, Vt = np.linalg.svd(D)

print("U:\n", U)
print("Singular values:", S)
print("V^T:\n", Vt)


U:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Singular values: [1. 1. 0.]
V^T:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


## 9) Exercises (practice)

Try solving these on your own:

1. Compute the dot product of `[2, 3, 4]` and `[1, 0, -1]`.
2. Find the rank and determinant of \( \begin{bmatrix} 1 & 2 \\ 3 & 6 \end{bmatrix} \).
3. Solve the system:  
   \( 2x + y = 5 \)  
   \( x - y = 1 \)
4. Find the eigenvalues of \( \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix} \).


## 10) Exercise solutions

Compare your answers here after attempting the exercises above.


In [10]:
# 1. Dot product
v1 = np.array([2, 3, 4])
v2 = np.array([1, 0, -1])
print("Dot product =", np.dot(v1, v2))

# 2. Rank and determinant
M = np.array([[1, 2], [3, 6]])
print("Rank =", np.linalg.matrix_rank(M))
print("Determinant =", np.linalg.det(M))

# 3. Solve linear system
A = np.array([[2, 1], [1, -1]])
b = np.array([5, 1])
x = np.linalg.solve(A, b)
print("Solution x =", x)

# 4. Eigenvalues
E = np.array([[2, 0], [0, 3]])
eigvals, eigvecs = np.linalg.eig(E)
print("Eigenvalues =", eigvals)


Dot product = -2
Rank = 1
Determinant = -3.330669073875464e-16
Solution x = [2. 1.]
Eigenvalues = [2. 3.]
